- name: Install Z shell packages
  become: yes
  apt: name={{ item }} update_cache=true
  with_items:
    - git
    - zsh

- name: Make zsh default shell
  become: yes
  shell: chsh -s $(which zsh) $(whoami)

- name: Install Oh my Zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh/
    dest=~/.oh-my-zsh/

- name: Install Zsh Syntax Highlighting
  git:
    repo=https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest=~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Copying zsh config
  template: src=config_files/zshrc.jinja2 dest=~/.zshrc
