- name: Copying SSH configuration
  copy: src=config_files/ssh_config dest=~/.ssh/config

- name: Setting Git global user email
  shell: git config --global user.email "karol.gruszczyk@gmail.com"

- name: Setting Git global user name
  shell: git config --global user.name karol-gruszczyk

- name: Setting Git global push default
  shell: git config --global push.default simple
