- name: Install python packages
  become: yes
  apt: name={{ item }} update_cache=true
  with_items:
    - git
    - python-dev
    - python3-dev
    - python-pip
    - python-virtualenv
    - ipython
