- name: Installing Google Chrome
  become: yes
  apt: deb=https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Installing Dropbox
  shell: cd ~ && wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf -

- name: Copying Template files
  shell: cp config_files/templates/* ~/Templates/
